### ISSUE TITLE
[GENERAL] Publish Spearbit complete audit on repo

### ISSUE THREAD

**Issue by Graeme-Code** [bcnmy/nexus#172]
### Inquiry or Suggestion

Context: We must publish the spearbit audit as acknowledgment of completetion on the nexus repo.

User Story:
As a vistor to the nexus repo, 
I can find the updated audit from spearbit,
So that I can assess vthe security work done on next.

Def done:
A user can find the audit on nexus repo. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by Graeme-Code** [comment]
- Confirm draft audit 
- [ ] Get high errors reduced to 3, with fixes for all 3. 
- [ ] medium 5.2.4 acknowledged but remove to informational. Missing EIP-165 supportsInterface not EIP-7579 compliant
- [ ] medium 5.2.7 fallback() can be used for direct unauthorized calls to fallback handlers.  (get it out of medium and removed)

**Comment by livingrockrises** [comment]
this should not be marked closed yet.

**Comment by Graeme-Code** [comment]
I got feedback from Rachael, its in discord though and struggling to get access.
