### ISSUE TITLE
Nexus code freeze and deploy on Base

### ISSUE THREAD

**Issue by livingrockrises** [bcnmy/nexus#189]
- deploy nexus on bunch of test networks and mainnets where bundler is ready.
- fix remappings, merge to main and make a release

**Comment by livingrockrises** [comment]
could be added in nexus-launchpad repo.. either ways

**Comment by Graeme-Code** [comment]
Reduce scope to Base and Base Sepholia

**Comment by livingrockrises** [comment]
code freeze is done
