### ISSUE TITLE
Infra Passkey Server

### ISSUE THREAD

**Issue by VGabriel45** [bcnmy/nexus#206]

**Comment by VGabriel45** [comment]
Related tickets https://github.com/orgs/bcnmy/projects/14/views/11?filterQuery=passkey&pane=issue&itemId=83260904&issue=bcnmy%7Csdk%7C77

**Comment by livingrockrises** [comment]
what is the status / need here?
please also update description

**Comment by filmakarov** [comment]
Closing as it should not be in public repo
