### ISSUE TITLE
[BUG] Npm installing repo with github url - HelperConfig missing in TestHelper.t.sol

### ISSUE THREAD

**Issue by Man-Jain** [bcnmy/nexus#223]
### Summary

Npm installing repo with github url scripts folder not getting downloaded

### Steps to Reproduce

1. yarn add https://github.com/bcnmy/nexus
2. Test cases giving error since they need HelperConfig from the scripts folder

<img width="674" alt="Screenshot 2024-11-28 at 09 54 51" src="https://github.com/user-attachments/assets/806dd70e-e5e8-4719-bd44-b41545dee130">

### Expected vs. Actual Behavior

The HelperConfig should be present. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by filmakarov** [comment]
Hey @Man-Jain 
Which branch are you on?
Scripts folder is present on the `dev` branch

**Comment by Man-Jain** [comment]
The folder is present on main as well. But the scripts folder is included in `.npmignore` so doing yarn add doesn't download that folder.

**Comment by filmakarov** [comment]
Fixed https://github.com/bcnmy/nexus/pull/230

**Comment by filmakarov** [comment]
Thanks @Man-Jain for noting that
