### ISSUE TITLE
[GENERAL] Create Biconomy-7579-Modules Repo

### ISSUE THREAD

**Issue by livingrockrises** [bcnmy/nexus#42]
### Inquiry or Suggestion

We should create a modules repo and have implementation of all the main modules like registry hook, permissions validator, executor product etc 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

**Comment by filmakarov** [comment]
Repo created.

https://github.com/bcnmy/smart-account-modules/tree/dev

Work started on the Permissions Validator
