### ISSUE TITLE
[FEATURE] Gaslite Gas Optimization Audit

### ISSUE THREAD

**Issue by pop-punk** [bcnmy/nexus#64]
### Feature or Improvement Description

Nexus Gas Optimization Audit

### Finding 1

File: BaseAccount.sol
https://github.com/bcnmy/nexus/blob/2d7a72a3f0338e047ad619d777ee069eb9b7a53e/contracts/base/BaseAccount.sol#L36-L41

Revise the revert condition to apply the not condition a single time when evaluating if the caller is `_ENTRYPOINT` or `address(this)`. 

```solidity
    modifier onlyEntryPointOrSelf() {
        if (!(msg.sender == _ENTRYPOINT || msg.sender == address(this))) {
            revert AccountAccessUnauthorized();
        }
        _;
    }
```

Gas savings: 12-17 gas units per call that uses `onlyEntryPointOrSelf` modifier.

---

### Finding 2

File: BaseAccount.sol
https://github.com/bcnmy/nexus/blob/2d7a72a3f0338e047ad619d777ee069eb9b7a53e/contracts/base/BaseAccount.sol#L71-L96

Utilize private function variables to change the behavior of `addDeposit` and `withdrawDepositTo` at the time of deployment rather than relying on an `EXTCODESIZE` check on `_ENTRYPOINT` on every call to determine if the contract exists.

```solidity
    function() private immutable _addDeposit;
    function(address,uint256) private immutable _withdrawDepositTo;

    constructor() {
        uint256 entryPointCodesize;

        /// @solidity memory-safe-assembly
        assembly {
            entryPointCodesize := extcodesize(_ENTRYPOINT)
        }

        if (entryPointCodesize > 0) {
            _addDeposit = _addDepositWithoutEntrypointCheck;
            _withdrawDepositTo = _withdrawDepositToWithoutEntrypointCheck;
        } else {
            _addDeposit = _addDepositWithEntrypointCheck;
            _withdrawDepositTo = _withdrawDepositToWithEntrypointCheck;
        }
    }

...

    /// @notice Adds deposit to the EntryPoint to fund transactions.
    function addDeposit() external payable virtual {
        _addDeposit();
    }

    function _addDepositWithEntrypointCheck() private {
        /// @solidity memory-safe-assembly
        assembly {
            // The EntryPoint has balance accounting logic in the `receive()` function.
            if iszero(mul(extcodesize(_ENTRYPOINT), call(gas(), _ENTRYPOINT, callvalue(), codesize(), 0x00, codesize(), 0x00))) {
                revert(codesize(), 0x00)
            } // For gas estimation.
        }
    }

    function _addDepositWithoutEntrypointCheck() private {
        /// @solidity memory-safe-assembly
        assembly {
            // The EntryPoint has balance accounting logic in the `receive()` function.
            if iszero(call(gas(), _ENTRYPOINT, callvalue(), codesize(), 0x00, codesize(), 0x00)) {
                revert(codesize(), 0x00)
            } // For gas estimation.
        }
    }

    /// @notice Withdraws ETH from the EntryPoint to a specified address.
    /// @param to The address to receive the withdrawn funds.
    /// @param amount The amount to withdraw.
    function withdrawDepositTo(address to, uint256 amount) external payable virtual onlyEntryPointOrSelf {
        _withdrawDepositTo(to, amount);
    }

    function _withdrawDepositToWithEntrypointCheck(address to, uint256 amount) private {
        /// @solidity memory-safe-assembly
        assembly {
            mstore(0x14, to) // Store the `to` argument.
            mstore(0x34, amount) // Store the `amount` argument.
            mstore(0x00, 0x205c2878000000000000000000000000) // `withdrawTo(address,uint256)`.
            if iszero(mul(extcodesize(_ENTRYPOINT), call(gas(), _ENTRYPOINT, 0, 0x10, 0x44, codesize(), 0x00))) {
                returndatacopy(mload(0x40), 0x00, returndatasize())
                revert(mload(0x40), returndatasize())
            }
            mstore(0x34, 0) // Restore the part of the free memory pointer that was overwritten.
        }
    }

    function _withdrawDepositToWithoutEntrypointCheck(address to, uint256 amount) private {
        /// @solidity memory-safe-assembly
        assembly {
            mstore(0x14, to) // Store the `to` argument.
            mstore(0x34, amount) // Store the `amount` argument.
            mstore(0x00, 0x205c2878000000000000000000000000) // `withdrawTo(address,uint256)`.
            if iszero(call(gas(), _ENTRYPOINT, 0, 0x10, 0x44, codesize(), 0x00)) {
                returndatacopy(mload(0x40), 0x00, returndatasize())
                revert(mload(0x40), returndatasize())
            }
            mstore(0x34, 0) // Restore the part of the free memory pointer that was overwritten.
        }
    }
```

Gas savings: 78 gas units per call when `_ENTRYPOINT` is deployed prior to a `BaseAccount`.

---

### Finding 3

File: ExecutionHelper.sol
https://github.com/bcnmy/nexus/blob/2d7a72a3f0338e047ad619d777ee069eb9b7a53e/contracts/base/ExecutionHelper.sol#L71-L119

Do not cache `executions.length`, move `Execution calldata exec` outside of the for loop for more efficient stack operations.

```solidity
    /// @notice Executes a batch of calls.
    /// @param executions An array of Execution structs each containing target, value, and calldata.
    /// @return result An array of results from each executed call.
    function _executeBatch(Execution[] calldata executions) internal returns (bytes[] memory result) {
        result = new bytes[](executions.length);

        Execution calldata exec;
        for (uint256 i; i < executions.length; i++) {
            exec = executions[i];
            result[i] = _execute(exec.target, exec.value, exec.callData);
        }
    }

    /// @notice Tries to execute a batch of calls and emits an event for each unsuccessful call.
    /// @param executions An array of Execution structs.
    /// @return result An array of results, with unsuccessful calls marked by events.
    function _tryExecuteBatch(Execution[] calldata executions) internal returns (bytes[] memory result) {
        result = new bytes[](executions.length);

        Execution calldata exec;
        for (uint256 i; i < executions.length; i++) {
            exec = executions[i];
            bool success;
            (success, result[i]) = _tryExecute(exec.target, exec.value, exec.callData);
            if (!success) emit TryExecuteUnsuccessful(i, result[i]);
        }
    }
```

Gas savings: 6 gas units per call plus 2 gas units per item in `executions`.

---

### Finding 4

File: Storage.sol
https://github.com/bcnmy/nexus/blob/2d7a72a3f0338e047ad619d777ee069eb9b7a53e/contracts/base/Storage.sol#L28-L29

Consider a zero mask on the upper 128 bits of the `_STORAGE_LOCATION` constant to reduce the deployed bytecode size by ~400 bytes. This may yield runtime gas savings in a future EVM environment where Verkle trees are utilized and the amount of contract bytecode accessed is a factor in the overall gas cost of a transaction [(see Vitalik notes on witness data)](https://notes.ethereum.org/@vbuterin/verkle_tree_eip#Witness-gas-costs).

```solidity
    bytes32 private constant _STORAGE_LOCATION = 0x00000000000000000000000000000000e7cbd8cb82505941fba30d1eb5b82f00;
```

Immediate gas savings in deployment costs, future gas savings in Verkle tree execution could be several hundreds of gas units per call.

---

### Finding 5

File: ModuleManager.sol
https://github.com/bcnmy/nexus/blob/2d7a72a3f0338e047ad619d777ee069eb9b7a53e/contracts/base/ModuleManager.sol#L39-L44

Do not cache `_getAccountStorage().executors` to optimize stack operations by avoiding duplicating the storage pointer.

```solidity
    /// @notice Ensures the message sender is a registered executor module.
    modifier onlyExecutorModule() virtual {
        if (!_getAccountStorage().executors.contains(msg.sender)) revert InvalidModule(msg.sender);
        _;
    }
```

Gas savings: 8 gas units per call to functions using `onlyExecutorModule`.

---

### Finding 6 

File: ModuleManager.sol
https://github.com/bcnmy/nexus/blob/2d7a72a3f0338e047ad619d777ee069eb9b7a53e/contracts/base/ModuleManager.sol#L46-L51

Do not cache `_getAccountStorage().validators` to optimize stack operations by avoiding duplicating the storage pointer.

```solidity
    /// @notice Ensures the specified address is a registered validator module.
    modifier onlyValidatorModule(address validator) virtual {
        if (!_getAccountStorage().validators.contains(validator)) revert InvalidModule(validator);
        _;
    }
```

Gas savings: 8 gas units per call to functions using `onlyValidatorModule`.

---

### Finding 7

File: ModuleManager.sol
https://github.com/bcnmy/nexus/blob/2d7a72a3f0338e047ad619d777ee069eb9b7a53e/contracts/base/ModuleManager.sol#L60-L111

The generic fallback function will either `return` or `revert` directly from the assembly blocks, as such calldata can be copied without concern for the free memory pointer or other data that currently exists in memory. Simplify memory allocation by storing calldata starting at zero and return data at zero for the revert or return.

```solidity
        if (calltype == CALLTYPE_STATIC) {
            assembly {
                calldatacopy(0, 0, calldatasize())

                // The msg.sender address is shifted to the left by 12 bytes to remove the padding
                // Then the address without padding is stored right after the calldata
                mstore(calldatasize(), shl(96, caller()))

                if iszero(staticcall(gas(), handler, 0, add(calldatasize(), 20), 0, 0)) {
                    returndatacopy(0, 0, returndatasize())
                    revert(0, returndatasize())
                }
                returndatacopy(0, 0, returndatasize())
                return(0, returndatasize())
            }
        }
        if (calltype == CALLTYPE_SINGLE) {
            assembly {
                calldatacopy(0, 0, calldatasize())

                // The msg.sender address is shifted to the left by 12 bytes to remove the padding
                // Then the address without padding is stored right after the calldata
                mstore(calldatasize(), shl(96, caller()))

                if iszero(call(gas(), handler, 0, 0, add(calldatasize(), 20), 0, 0)) {
                    returndatacopy(0, 0, returndatasize())
                    revert(0, returndatasize())
                }
                returndatacopy(0, 0, returndatasize())
                return(0, returndatasize())
            }
        }
```

Gas savings: 115 gas units on fallback.

---

### Finding 8

File: ModuleManager.sol
https://github.com/bcnmy/nexus/blob/2d7a72a3f0338e047ad619d777ee069eb9b7a53e/contracts/base/ModuleManager.sol#L168-L169

Do not cache `_getAccountStorage().validators` to optimize stack operations by avoiding duplicating the storage pointer.

```solidity
        _getAccountStorage().validators.push(validator);
```

Gas savings: ~6 gas units on adding a validator.

---

### Finding 9

File: ModuleManager.sol
https://github.com/bcnmy/nexus/blob/2d7a72a3f0338e047ad619d777ee069eb9b7a53e/contracts/base/ModuleManager.sol#L173-L189

Cache the `_getAccountStorage().validators` storage pointer to avoid multiple lookups. Revise the determination of whether the validator being removed is the last validator by checking if the previous item in the linked list is the sentinel address first. If it is not the sentinel address then there is at least one other item in the list, if it is the sentinel address then check if the item being removed's linked item is the sentinel address. If the item being removed's linked item is the sentinel address then it is the last item in the list and removal should revert, otherwise allow removal.

```solidity
    /// @dev Uninstalls a validator module /!\ ensuring the account retains at least one validator.
    /// @param validator The address of the validator to be uninstalled.
    /// @param data De-initialization data to configure the validator upon uninstallation.
    function _uninstallValidator(address validator, bytes calldata data) internal virtual {
        SentinelListLib.SentinelList storage validators = _getAccountStorage().validators;

        (address prev, bytes memory disableModuleData) = abi.decode(data, (address, bytes));

        // Check if the account has at least one validator installed before proceeding
        // Having at least one validator is a requirement for the account to function properly
        if (prev == address(0x01)) {
            if(validators.getNext(validator) == address(0x01)) {
                revert CannotRemoveLastValidator();
            }
        }

        validators.pop(prev, validator);

        IValidator(validator).onUninstall(disableModuleData);
    }
```

Gas savings: 3,504 gas units on successful removal

NOTE: Test `test_UninstallModule_Success` was not actually removing `mockValidator` since it was not installed and `prev` was being passed as `address(0)` because `findPrevious` does not fall back to the sentinel address. The below revision ensures that `mockValidator` is installed to validate gas savings on removal.

```solidity
    function test_UninstallModule_Success() public {
        MockValidator newMockValidator = new MockValidator();

        bytes memory installCallData = abi.encodeWithSelector(
            IModuleManager.installModule.selector, MODULE_TYPE_VALIDATOR, address(newMockValidator), ""
        );
        installModule(installCallData, MODULE_TYPE_VALIDATOR, address(newMockValidator), EXECTYPE_DEFAULT);

        installCallData = abi.encodeWithSelector(
            IModuleManager.installModule.selector, MODULE_TYPE_VALIDATOR, address(mockValidator), ""
        );
        installModule(installCallData, MODULE_TYPE_VALIDATOR, address(mockValidator), EXECTYPE_DEFAULT);

        assertTrue(
            BOB_ACCOUNT.isModuleInstalled(MODULE_TYPE_VALIDATOR, address(newMockValidator), ""),
            "New Mock Module should be installed initially"
        );

        assertTrue(
            BOB_ACCOUNT.isModuleInstalled(MODULE_TYPE_VALIDATOR, address(mockValidator), ""),
            "Mock Module should be installed initially"
        );

        (address[] memory array,) = BOB_ACCOUNT.getValidatorsPaginated(address(0x1), 100);
        address remove = address(mockValidator);
        address prev = SentinelListHelper.findPrevious(array, remove);
        // If return is address(0), prev should be the sentinel address
        if (prev == address(0)) prev = address(0x01);

        bytes memory callData = abi.encodeWithSelector(
            IModuleManager.uninstallModule.selector,
            MODULE_TYPE_VALIDATOR,
            address(mockValidator),
            // uninstallData needs to provide prev module address with data to uninstall
            abi.encode(prev, "")
        );

        uninstallModule(callData, EXECTYPE_DEFAULT);

        assertFalse(
            BOB_ACCOUNT.isModuleInstalled(MODULE_TYPE_VALIDATOR, address(mockValidator), ""),
            "Module should not be installed anymore"
        );
        assertTrue(
            BOB_ACCOUNT.isModuleInstalled(MODULE_TYPE_VALIDATOR, address(newMockValidator), ""),
            "Module should be installed"
        );
    }
```

---

### Finding 10

File: ModuleManager.sol
https://github.com/bcnmy/nexus/blob/2d7a72a3f0338e047ad619d777ee069eb9b7a53e/contracts/base/ModuleManager.sol#L200-L201

Do not cache `_getAccountStorage().executors` to optimize stack operations by avoiding duplicating the storage pointer.

```solidity
        _getAccountStorage().executors.push(executor);
```

Gas savings: ~6 gas units on adding a executor.

---

### Finding 11

File: AccountFactory.sol
https://github.com/bcnmy/nexus/blob/2d7a72a3f0338e047ad619d777ee069eb9b7a53e/contracts/factory/AccountFactory.sol#L42-L73

The `salt` value can be more efficiently hashed using assembly to `calldatacopy` all data after the function selector.

```solidity
    /// @notice Creates a new Nexus with a specific validator and initialization data.
    /// @param validationModule The address of the validation module to configure the new Nexus.
    /// @param moduleInstallData Initialization data for configuring the validation module.
    /// @param index An identifier used to generate a unique deployment address.
    /// @return The address of the newly created Nexus.
    /// @dev Deploys a new Nexus using a deterministic address based on the input parameters.
    function createAccount(address validationModule, bytes calldata moduleInstallData, uint256 index) external payable returns (address payable) {
        bytes32 salt;

        assembly {
            let ptr := mload(0x40)
            let calldataLength := sub(calldatasize(), 0x04)
            mstore(0x40, add(ptr, calldataLength))
            calldatacopy(ptr, 0x04, calldataLength)
            salt := keccak256(ptr, calldataLength)
        }

        (bool alreadyDeployed, address account) = LibClone.createDeterministicERC1967(msg.value, ACCOUNT_IMPLEMENTATION, salt);

        if (!alreadyDeployed) {
            INexus(account).initialize(validationModule, moduleInstallData);
            emit AccountCreated(account, validationModule, moduleInstallData);
        }
        return payable(account);
    }

    /// @notice Computes the expected address of a Nexus contract using the factory's deterministic deployment algorithm.
    /// @param validationModule The address of the module to be used in the Nexus.
    /// @param moduleInstallData The initialization data for the module.
    /// @param index The index or type of the module, used for generating the deployment address.
    /// @return expectedAddress The expected address at which the Nexus contract will be deployed if the provided parameters are used.
    /// @dev This function allows for address prediction without deploying the Nexus.
    function getCounterFactualAddress(
        address validationModule,
        bytes calldata moduleInstallData,
        uint256 index
    ) external view returns (address payable expectedAddress) {
        bytes32 salt;

        assembly {
            let ptr := mload(0x40)
            let calldataLength := sub(calldatasize(), 0x04)
            mstore(0x40, add(ptr, calldataLength))
            calldatacopy(ptr, 0x04, calldataLength)
            salt := keccak256(ptr, calldataLength)
        }

        expectedAddress = payable(LibClone.predictDeterministicAddressERC1967(ACCOUNT_IMPLEMENTATION, salt, address(this)));
    }
```

Gas savings: ~100 gas units on account creation.

---

### Finding 12

File: K1Validator.sol
https://github.com/bcnmy/nexus/blob/2d7a72a3f0338e047ad619d777ee069eb9b7a53e/contracts/modules/validators/K1Validator.sol#L55-L62

Cache the `smartAccountOwners[userOp.sender]` value to avoid duplicate hashing of the storage slot if the first signature validation is unsuccessful. Return early if signature is valid and leave a default return of failed at the end of the function for more efficient stack utilization.

```solidity
    function validateUserOp(PackedUserOperation calldata userOp, bytes32 userOpHash) external view returns (uint256) {
        address owner = smartAccountOwners[userOp.sender];
        if(owner.isValidSignatureNow(ECDSA.toEthSignedMessageHash(userOpHash), userOp.signature)) {
            return VALIDATION_SUCCESS;
        }
        if (owner.isValidSignatureNow(userOpHash, userOp.signature)) {
            return VALIDATION_SUCCESS;
        }
        return VALIDATION_FAILED;
    }
```

---

### Finding 13

File: Nexus.sol
https://github.com/bcnmy/nexus/blob/2d7a72a3f0338e047ad619d777ee069eb9b7a53e/contracts/Nexus.sol#L58-L75

Utilize a named return value for the `validateUserOp` return.

```solidity
    function validateUserOp(
        PackedUserOperation calldata userOp,
        bytes32 userOpHash,
        uint256 missingAccountFunds
    ) external virtual payPrefund(missingAccountFunds) onlyEntryPoint returns (uint256 validationData) {
        address validator;
        uint256 nonce = userOp.nonce;
        assembly {
            validator := shr(96, nonce)
        }
        // Check if validator is not enabled. If not, return VALIDATION_FAILED.

        if (!_isValidatorInstalled(validator)) return VALIDATION_FAILED;

        // bubble up the return value of the validator module
        validationData = IValidator(validator).validateUserOp(userOp, userOpHash);
    }
```

Gas savings: 11 gas units per call to `validateUserOp`.

---

### Finding 14

File: Nexus.sol
https://github.com/bcnmy/nexus/blob/2d7a72a3f0338e047ad619d777ee069eb9b7a53e/contracts/Nexus.sol#L245-L258

Join the `callType` and `execType` evaluations into a single return statement so that short-circuiting may be applied to evaluations. Consider the ordering within `callType` and `execType` based on expected usage.

```solidity
    /// @notice Determines if a specific execution mode is supported.
    /// @param mode The execution mode to evaluate.
    /// @return isSupported True if the execution mode is supported, false otherwise.
    function supportsExecutionMode(ExecutionMode mode) external view virtual returns (bool isSupported) {
        (CallType callType, ExecType execType, , ) = mode.decode();

        // Return true if both the call type and execution type are supported.
        return (callType == CALLTYPE_BATCH || callType == CALLTYPE_SINGLE) 
            && (execType == EXECTYPE_DEFAULT || execType == EXECTYPE_TRY);
    }
```

Gas savings: ~25 gas units.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by pop-punk** [comment]
Apologies, finding 2 should be:

```solidity
function() internal immutable _addDeposit;
function(address,uint256) internal immutable _withdrawDepositTo;
```

**Comment by pop-punk** [comment]
> > on finding 2
> > `function() private immutable _addDeposit;`
> > compiler complains with Invalid visibility, can only be "external" or "internal".
> 
> It is also safe to assume entrypoint would always be deployed prior to BaseAccount.


If it's safe to assume entrypoint is deployed, then you don't need a version of the functions with the entrypoint check ... which is what was being done with `mul(extcodesize(_ENTRYPOINT)`

**Comment by pop-punk** [comment]
> on finding 4 if we go ahead we would lose relation to keccak256(abi.encode(uint256(keccak256(bytes("biconomy.storage.Nexus"))) - 1)) & ~bytes32(uint256(0xff))
> 
> also, if the more zeros the better then to what extend I can add more zeros in below? 0x00000000000000000000000000000000e7cbd8cb82505941fba30d1eb5b82f00

given your current implementation, you could probably get away with all zeroes since the only contract that uses it is ModuleManager and it doesn't have any storage slots defined. Safe is a base slot where you cannot reasonably expect to get there from contract storage slot allocations

**Comment by livingrockrises** [comment]
> > > on finding 2
> > > `function() private immutable _addDeposit;`
> > > compiler complains with Invalid visibility, can only be "external" or "internal".
> > 
> > 
> > It is also safe to assume entrypoint would always be deployed prior to BaseAccount.
> 
> If it's safe to assume entrypoint is deployed, then you don't need a version of the functions with the entrypoint check, which is what was being done with `mul(extcodesize(_ENTRYPOINT)`

yes @pop-punk I am planning to keep only one version which does not do extcodesize.

**Comment by livingrockrises** [comment]
> > on finding 4 if we go ahead we would lose relation to keccak256(abi.encode(uint256(keccak256(bytes("biconomy.storage.Nexus"))) - 1)) & ~bytes32(uint256(0xff))
> > also, if the more zeros the better then to what extend I can add more zeros in below? 0x00000000000000000000000000000000e7cbd8cb82505941fba30d1eb5b82f00
> 
> given your current implementation, you could probably get away with all zeroes since the only contract that uses it is ModuleManager and it doesn't have any storage slots defined. Safe is a base slot where you cannot reasonably expect to get there from contract storage slot allocations

hmm got it, I would prefer fairly unstructured storage. will leave this acknowledged for now and layer maybe change our storage slot and compare gas again through future benchmarks. cc @pop-punk

**Comment by livingrockrises** [comment]
closing this a completed
